"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

https://bitbucket.org/ronaldoussoren/py2app/issues/219/new-mach-o-header-is-too-large-to-relocate
"""

from setuptools import setup

APP = ['id3tag.py']
DATA_FILES = ["resources/id3tag.gif"]
OPTIONS = {
    "iconfile": "resources/id3tag.icns",
    "packages": ["PIL"]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
